<?php

/**
 * Implements hook_node_presave().
 */
function sbi_custom_node_presave($node) {
  if($node->type == 'sbi_premium') {
    $product = commerce_product_load($node->field_product_insurance['und'][0]['product_id']);
   $product->commerce_price['und'][0]['amount'] = "1200";
    commerce_product_save($product);
  }
}

function sbi_custom_preprocess_commerce_line_item_summary(&$variables) {
  $variables['total'] = $variables['total_raw'] . 'INR';
}

/**
 * Implements hook_form_alter().
 */
function sbi_custom_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'sbi_premium_node_form':
    $form['title_field']['#access'] = FALSE;
    $form['actions']['submit']['#value'] = "Calculate Premium";
      $form['actions']['preview']['#access'] = FALSE;
      $form['field_product_insurance']['#access'] = FALSE;
    break;
  }
}

/**
 * Implements hook_block_info().
 */
function sbi_custom_block_info() {
  $blocks['sbi_premium_block'] = array(
    'info' => t('SBI Premium Block'),
    'cache' => DRUPAL_NO_CACHE
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function sbi_custom_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'sbi_premium_block':
      $block['subject'] = t('');
      $block['content'] = _sbi_custom_premium_block();
      break;
  }
  return $block;
}

function _sbi_custom_premium_block() {
  $html = '';
  $html .= '<div>';
  $html .= '<ul class="sbi_premier">';
  $html .= '<li><a href="#" class="sbi-icon-car">Car</a></li><li><a href="#" class="sbi-icon-bike">2-Wheeler</a></li><li><a href="#" class="sbi-icon-health">Health</a></li><li><a href="#" class="sbi-icon-home">Home</a></li><li><a href="node/add/sbi-premium" class="sbi-icon-travel">Travel</a></li><li><a href="#" class="sbi-icon-accident">Personal Accident</a></li><li><a href="#" class="sbi-icon-hospital">Hospital Daily Cash</a></li><li><a href="#" class="sbi-icon-illness">Criticl Illness</a></li><li><a href="#" class="sbi-icon-arogya">Arogya Premier</a></li>';
  $html .= '</ul>';
  $html .= '</div>';

  return $html;
}

function sbi_custom_inline_entity_form_entity_form_alter(&$entity_form, &$form_state) {
  if($entity_form['#entity']->type == 'sbi_premier') {
    $entity_form['commerce_price']['und'][0]['amount']['#default_value'] = '100';
  }
}

function sbi_custom_commerce_order_presave($order) {
  if(!empty($order->commerce_line_items['und'][0]['line_item_id'])) {
    $line_item_id = $order->commerce_line_items['und'][0]['line_item_id'];
    $line_item_load = commerce_line_item_load($line_item_id);
    $product_id = $line_item_load->commerce_product['und'][0]['product_id'];
    if(!empty($product_id)) {   
      $query = db_select('field_data_field_product_insurance', 'fpi')
      ->fields('fpi', array('entity_id '))
      ->condition('entity_type', 'node', '=')
      ->condition('bundle', 'sbi_premium', '=')
      ->condition('field_product_insurance_product_id', $product_id, '=')
      ->execute()
      ->fetchAll();
      $result = $query[0]->entity_id;
      $order->field_node_info[LANGUAGE_NONE][0]['target_id'] = $result; 
    }
  }
}

?>
